# Generated by Django 2.0.2 on 2018-09-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Razão/Nome')),
                ('fantasia', models.CharField(blank=True, max_length=40, verbose_name='Fantasia')),
                ('cep', models.CharField(blank=True, max_length=12, null=True, verbose_name='CEP')),
                ('endereco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=40, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
    ]
