# Generated by Django 2.0.2 on 2018-09-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180917_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descricao_empresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição Empresa'),
        ),
    ]
