# Generated by Django 2.0.2 on 2018-09-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20180906_0007'),
        ('checkout', '0006_auto_20180909_2107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart_key', 'product', 'cor', 'tamanho')},
        ),
    ]
