# Generated by Django 2.0.2 on 2018-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocao',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promoções', verbose_name='Imagem'),
        ),
    ]
