# Generated by Django 2.0.2 on 2018-03-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20180228_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='image',
        ),
    ]
