# Generated by Django 2.0.2 on 2018-08-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180224_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carroucel',
            field=models.BooleanField(default=False, verbose_name='Ir para Carrocel principal'),
        ),
    ]
