# Generated by Django 2.0.2 on 2018-09-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_descricao_completa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carroucel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=60, verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='products', verbose_name='Imagem')),
                ('category', models.ForeignKey(on_delete='Categoria', to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Carrocel',
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=20, verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=10, verbose_name='Tamanho')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='carroucel',
        ),
        migrations.AddField(
            model_name='tamanho',
            name='product',
            field=models.ForeignKey(on_delete='Produto', to='catalog.Product'),
        ),
        migrations.AddField(
            model_name='cor',
            name='product',
            field=models.ForeignKey(on_delete='Produto', to='catalog.Product'),
        ),
    ]
