# Generated by Django 2.0.2 on 2018-09-03 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180902_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cor',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tamanho',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='cor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Cor', to='catalog.Cor', verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='product',
            name='tamanho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tamanho', to='catalog.Tamanho', verbose_name='Tamanho'),
        ),
    ]
