# Generated by Django 2.0.2 on 2018-09-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20180902_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tamanho',
        ),
        migrations.AlterField(
            model_name='cor',
            name='cor',
            field=models.CharField(max_length=20, verbose_name='Cor'),
        ),
    ]
