# Generated by Django 2.0.2 on 2018-09-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180902_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cor',
            field=models.ManyToManyField(to='catalog.Cor'),
        ),
        migrations.AddField(
            model_name='product',
            name='tamanho',
            field=models.ManyToManyField(to='catalog.Tamanho'),
        ),
    ]
