# Generated by Django 2.0.2 on 2018-09-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180904_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='product',
            name='tamanho',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tamanho'),
        ),
    ]
