# Generated by Django 2.0.2 on 2018-09-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20180905_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cor',
        ),
        migrations.AddField(
            model_name='product',
            name='cor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cor'),
        ),
    ]
